os: linux
dist: focal
language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt

sudo: true

before_install:
    - pip install pytest pytest-cov
    - pip install coveralls

    - sudo apt-get update
    - sudo apt install python3-nose python3-coverage

    - curl https://couchdb.apache.org/repo/keys.asc | gpg --dearmor > couchdb-repo-keyring.gnp && sudo mv couchdb-repo-keyring.gnp /usr/share/keyrings/
    - echo "deb [signed-by=/usr/share/keyrings/couchdb-repo-keyring.gnp] https://apache.jfrog.io/artifactory/couchdb-deb focal main" > couchdb.list && sudo mv couchdb.list /etc/apt/sources.list.d/
    - apt update
    - apt install couchdb

before_script:
   - source set_pythonpath.sh

script:
   - nosetests3 --with-coverage src/Guardian/*
   - python3.8 -m unittest Guardian/testGuardian.py

after_success:
    - coveralls