os: linux
dist: xenial
language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt

#services:

#before_script:

sudo: true

before_install:
    - pip install pytest pytest-cov
    - pip install coveralls

    - sudo apt-get update
    - sudo apt-get --no-install-recommends -y install build-essential pkg-config erlang libicu-dev libmozjs185-dev libcurl4-openssl-dev
    - erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().' -noshell
    - wget https://archive.apache.org/dist/couchdb/source/2.0.0/apache-couchdb-2.0.0.tar.gz
    - tar -xvzf apache-couchdb-2.0.0.tar.gz
    - cd apache-couchdb-2.0.0/
    - sudo ./configure
    - sudo make release
    - find rel/couchdb -type d -exec chmod 0770 {} \;
    - sudo chmod 0644 rel/couchdb/etc/*
    - sudo rel/couchdb/bin/couchdb 2>/dev/null &
    - cd ..


script:
   - source set_pythonpath.sh && nosetests3 --with-coverage src/Guardian/*
   - python3.6 -m unittest Guardian/testGuardian.py


after_success:
    - coveralls