os: linux
dist: focal
language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt

sudo: true

before_install:
    - pip install pytest pytest-cov
    - pip install coveralls

    - sudo apt-get update
    - sudo apt install python3-nose python3-coverage

    - sudo apt-get --no-install-recommends -y install build-essential pkg-config erlang libicu-dev libcurl4-openssl-dev
    - sudo apt -y install libmozjs-68-0 libmozjs-68-dev libmozjs-52-0 libmozjs-52-dev
    - erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().' -noshell
    - wget https://dlcdn.apache.org/couchdb/source/3.2.0/apache-couchdb-3.2.0.tar.gz
    - tar -xvzf apache-couchdb-3.2.0.tar.gz
    - cd apache-couchdb-3.2.0/
    - sudo ./configure
    - sudo make release
    - find rel/couchdb -type d -exec chmod 0770 {} \;
    - sudo chmod 0644 rel/couchdb/etc/*
    - sudo rel/couchdb/bin/couchdb 2>/dev/null &
    - cd ..

before_script:
   - source set_pythonpath.sh

script:
   - nosetests3 --with-coverage src/Guardian/*
   - python3.8 -m unittest Guardian/testGuardian.py

after_success:
    - coveralls