site_name: Serverless Containers documentation
nav:
    - Introduction: index.md
    - Use case: use_case.md
    - Architecture: architecture.md
    - Deployment: deployment.md
    - Quickstart: quickstart.md
    - Configuration: configuration.md
    - Sponsors: sponsors.md
    - Homepage (external): http://bdwatchdog.dec.udc.es/serverless/index.html
    - Source code (external): code/src/index.html


#theme: readthedocs
#theme: mkdocs

theme:
    name: material
    #custom_dir: 'custom_theme/'
    favicon: 'img/icon.png'

# Repository
repo_name: 'JonatanEnes/ServerlessContainers'
repo_url: 'https://github.com/JonatanEnes/ServerlessContainers'

# Copyright
copyright: 'Copyright &copy; 2018 - 2020 Jonatan Enes'

markdown_extensions:
  - attr_list