verbose: no

influxdb_host: "montoxo.des.udc.es"
influxdb_bucket: "compute2"
influxdb_token: "MyToken"
influxdb_org: "MyOrg"

prediction_methods: "sgdregressor"
model_variables: "user_load,system_load"

host_timestamps_dir: "./conf/WattWizard/host"
container_timestamps_dir: "./conf/WattWizard/container"
host_train_files: "all"
container_train_files: "all"

plot_time_series: no
plot_time_series_dir: "./conf/WattWizard/time_series"